-- public.about_me definition

-- Drop table

-- DROP TABLE public.about_me;

CREATE TABLE public.about_me (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	created_at timestamptz NOT NULL DEFAULT now(),
	"name" text NULL,
	profession text NULL,
	current_job text NULL,
	"desc" text NULL,
	motivation text NULL,
	current_office_url text NULL,
	profile_img text NULL,
	CONSTRAINT about_me_pkey PRIMARY KEY (id)
);