-- public.project_tech definition

-- Drop table

-- DROP TABLE public.project_tech;

CREATE TABLE public.project_tech (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	project_id int8 NOT NULL,
	tech text NULL,
	url text NULL,
	CONSTRAINT project_tech_pkey PRIMARY KEY (id)
);


-- public.project_tech foreign keys

ALTER TABLE public.project_tech ADD CONSTRAINT public_project_tech_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id);